export default // 20210604103344
// https://api.github.com/users/mkstamin/followers

[
    {
        login: 'hossainrabbi',
        id: 67089472,
        node_id: 'MDQ6VXNlcjY3MDg5NDcy',
        avatar_url: 'https://avatars.githubusercontent.com/u/67089472?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/hossainrabbi',
        html_url: 'https://github.com/hossainrabbi',
        followers_url: 'https://api.github.com/users/hossainrabbi/followers',
        following_url: 'https://api.github.com/users/hossainrabbi/following{/other_user}',
        gists_url: 'https://api.github.com/users/hossainrabbi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/hossainrabbi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/hossainrabbi/subscriptions',
        organizations_url: 'https://api.github.com/users/hossainrabbi/orgs',
        repos_url: 'https://api.github.com/users/hossainrabbi/repos',
        events_url: 'https://api.github.com/users/hossainrabbi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/hossainrabbi/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'alakdeybabude',
        id: 63889985,
        node_id: 'MDQ6VXNlcjYzODg5OTg1',
        avatar_url: 'https://avatars.githubusercontent.com/u/63889985?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/alakdeybabude',
        html_url: 'https://github.com/alakdeybabude',
        followers_url: 'https://api.github.com/users/alakdeybabude/followers',
        following_url: 'https://api.github.com/users/alakdeybabude/following{/other_user}',
        gists_url: 'https://api.github.com/users/alakdeybabude/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/alakdeybabude/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/alakdeybabude/subscriptions',
        organizations_url: 'https://api.github.com/users/alakdeybabude/orgs',
        repos_url: 'https://api.github.com/users/alakdeybabude/repos',
        events_url: 'https://api.github.com/users/alakdeybabude/events{/privacy}',
        received_events_url: 'https://api.github.com/users/alakdeybabude/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'Mujahid9396',
        id: 47620872,
        node_id: 'MDQ6VXNlcjQ3NjIwODcy',
        avatar_url: 'https://avatars.githubusercontent.com/u/47620872?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Mujahid9396',
        html_url: 'https://github.com/Mujahid9396',
        followers_url: 'https://api.github.com/users/Mujahid9396/followers',
        following_url: 'https://api.github.com/users/Mujahid9396/following{/other_user}',
        gists_url: 'https://api.github.com/users/Mujahid9396/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Mujahid9396/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Mujahid9396/subscriptions',
        organizations_url: 'https://api.github.com/users/Mujahid9396/orgs',
        repos_url: 'https://api.github.com/users/Mujahid9396/repos',
        events_url: 'https://api.github.com/users/Mujahid9396/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Mujahid9396/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'AbuMusaa',
        id: 75556882,
        node_id: 'MDQ6VXNlcjc1NTU2ODgy',
        avatar_url: 'https://avatars.githubusercontent.com/u/75556882?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/AbuMusaa',
        html_url: 'https://github.com/AbuMusaa',
        followers_url: 'https://api.github.com/users/AbuMusaa/followers',
        following_url: 'https://api.github.com/users/AbuMusaa/following{/other_user}',
        gists_url: 'https://api.github.com/users/AbuMusaa/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/AbuMusaa/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/AbuMusaa/subscriptions',
        organizations_url: 'https://api.github.com/users/AbuMusaa/orgs',
        repos_url: 'https://api.github.com/users/AbuMusaa/repos',
        events_url: 'https://api.github.com/users/AbuMusaa/events{/privacy}',
        received_events_url: 'https://api.github.com/users/AbuMusaa/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'MehedilslamRipon',
        id: 51530291,
        node_id: 'MDQ6VXNlcjUxNTMwMjkx',
        avatar_url: 'https://avatars.githubusercontent.com/u/51530291?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/MehedilslamRipon',
        html_url: 'https://github.com/MehedilslamRipon',
        followers_url: 'https://api.github.com/users/MehedilslamRipon/followers',
        following_url: 'https://api.github.com/users/MehedilslamRipon/following{/other_user}',
        gists_url: 'https://api.github.com/users/MehedilslamRipon/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/MehedilslamRipon/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/MehedilslamRipon/subscriptions',
        organizations_url: 'https://api.github.com/users/MehedilslamRipon/orgs',
        repos_url: 'https://api.github.com/users/MehedilslamRipon/repos',
        events_url: 'https://api.github.com/users/MehedilslamRipon/events{/privacy}',
        received_events_url: 'https://api.github.com/users/MehedilslamRipon/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'Magicianred',
        id: 4624113,
        node_id: 'MDQ6VXNlcjQ2MjQxMTM=',
        avatar_url: 'https://avatars.githubusercontent.com/u/4624113?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Magicianred',
        html_url: 'https://github.com/Magicianred',
        followers_url: 'https://api.github.com/users/Magicianred/followers',
        following_url: 'https://api.github.com/users/Magicianred/following{/other_user}',
        gists_url: 'https://api.github.com/users/Magicianred/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Magicianred/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Magicianred/subscriptions',
        organizations_url: 'https://api.github.com/users/Magicianred/orgs',
        repos_url: 'https://api.github.com/users/Magicianred/repos',
        events_url: 'https://api.github.com/users/Magicianred/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Magicianred/received_events',
        type: 'User',
        site_admin: false,
    },
    {
        login: 'mahtamun-hoque-fahim',
        id: 72432456,
        node_id: 'MDQ6VXNlcjcyNDMyNDU2',
        avatar_url: 'https://avatars.githubusercontent.com/u/72432456?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/mahtamun-hoque-fahim',
        html_url: 'https://github.com/mahtamun-hoque-fahim',
        followers_url: 'https://api.github.com/users/mahtamun-hoque-fahim/followers',
        following_url: 'https://api.github.com/users/mahtamun-hoque-fahim/following{/other_user}',
        gists_url: 'https://api.github.com/users/mahtamun-hoque-fahim/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/mahtamun-hoque-fahim/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/mahtamun-hoque-fahim/subscriptions',
        organizations_url: 'https://api.github.com/users/mahtamun-hoque-fahim/orgs',
        repos_url: 'https://api.github.com/users/mahtamun-hoque-fahim/repos',
        events_url: 'https://api.github.com/users/mahtamun-hoque-fahim/events{/privacy}',
        received_events_url: 'https://api.github.com/users/mahtamun-hoque-fahim/received_events',
        type: 'User',
        site_admin: false,
    },
];
