// 20210604102722
// https://api.github.com/users/mkstamin

export default {
    login: 'mkstamin',
    id: 42057721,
    node_id: 'MDQ6VXNlcjQyMDU3NzIx',
    avatar_url: 'https://avatars.githubusercontent.com/u/42057721?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mkstamin',
    html_url: 'https://github.com/mkstamin',
    followers_url: 'https://api.github.com/users/mkstamin/followers',
    following_url: 'https://api.github.com/users/mkstamin/following{/other_user}',
    gists_url: 'https://api.github.com/users/mkstamin/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mkstamin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mkstamin/subscriptions',
    organizations_url: 'https://api.github.com/users/mkstamin/orgs',
    repos_url: 'https://api.github.com/users/mkstamin/repos',
    events_url: 'https://api.github.com/users/mkstamin/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mkstamin/received_events',
    type: 'User',
    site_admin: false,
    name: 'Mks Tamin',
    company: null,
    blog: 'https://mkstamin.live/',
    location: 'Bogura,Bangladesh',
    email: null,
    hireable: null,
    bio: 'web-developer & JavaScript worshiper',
    twitter_username: 'MksTamin',
    public_repos: 23,
    public_gists: 0,
    followers: 7,
    following: 14,
    created_at: '2018-08-03T06:41:40Z',
    updated_at: '2021-06-03T06:24:43Z',
};
